###
GET http://10.120.32.68/app/api/v1/kategoria


###get kategoria by id
GET http://10.120.32.68/app/api/v1/kategoria/1


### get kategoria by name
GET http://10.120.32.68/app/api/v1/kategoria/name/laktoositon


### uusi kategoria
POST http://10.120.32.68/app/api/v1/kategoria
Content-Type: application/json

{
    "kategoria_nimi": "素食"
}

###Delete kategoria by id
DELETE http://10.120.32.68/app/api/v1/kategoria/2


###Update kategoria by id
PUT http://10.120.32.68/app/api/v1/kategoria/3
Content-Type: application/json

{
    "kategoria_nimi": "haloo"
}
