###
GET http://10.120.32.68/app/api/v1/kategoria_tuote


###get Kategoria_tuote by id
GET http://10.120.32.68/app/api/v1/kategoria_tuote/465

###get Kategoria_tuote by tuote_id
GET http://10.120.32.68/app/api/v1/kategoria_tuote/tuote/17

### get kategoria by tuote ja kategoriatuote_id
GET http://10.120.32.68/app/api/v1/kategoria_tuote/336/3

###get Kategoria_tuote by kategoria_id
GET http://10.120.32.68/app/api/v1/kategoria_tuote/kategoria/4


### uusi Kategoria_tuote
POST http://10.120.32.68/app/api/v1/kategoria_tuote
Content-Type: application/json

{

    "tuote_id": "321",
    "kategoria_id": "13"

}


###Delete Kategoria_tuote by id
DELETE http://10.120.32.68/app/api/v1/kategoria_tuote/461


###Update Kategoria_tuote by id
PUT http://10.120.32.68/app/api/v1/kategoria_tuote/4
Content-Type: application/json

{
    "tuote_id": "3",
    "kategoria_id": "1"
}
