###
GET http://10.120.32.68/app/api/v1/suosikit


###get suosikit by asiakas_id
GET http://10.120.32.68/app/api/v1/suosikit/12


### uusi suosikit
POST http://10.120.32.68/app/api/v1/suosikit
Content-Type: application/json

{
    "asiakas_id": "3",
    "tuote_id": "3"
}

###Delete suosikit by asiakas_id and tuote_id
DELETE http://10.120.32.68/app/api/v1/suosikit/3/3

###Delete suosikit by asiakas_id and tuote_id
DELETE http://10.120.32.68/app/api/v1/suosikit/12/18
