###
GET http://localhost:3000/api/v1/tilaus



###get tilaus by tulaus_id
GET http://localhost:3000/api/v1/tilaus/1


###get tilaus by asiakas_id
GET http://localhost:3000/api/v1/tilaus/asiakas/12


### uusi tilaus
POST http://localhost:3000/api/v1/tilaus
Content-Type: application/json

{
    "asiakas_id": "5"
}


###Delete tilaus by tilaus_id
DELETE http://localhost:3000/api/v1/tilaus/1


###Update tilaus by tilaus_id
PUT http://localhost:3000/api/v1/tilaus/2
Content-Type: application/json

{
    "asiakas_id": "5"
}
