###
GET http://10.120.32.68/app/api/v1/tilaus



###get tilaus by tulaus_id
GET http://10.120.32.68/app/api/v1/tilaus/1


###get tilaus by asiakas_id
GET http://10.120.32.68/app/api/v1/tilaus/asiakas/69


### uusi tilaus
POST http://10.120.32.68/app/api/v1/tilaus
Content-Type: application/json

{
    "asiakas_id": "69"
}


###Delete tilaus by tilaus_id
DELETE http://10.120.32.68/app/api/v1/tilaus/1


###Update tilaus by tilaus_id
PUT http://10.120.32.68/app/api/v1/tilaus/2
Content-Type: application/json

{
    "asiakas_id": "5"
}
