###
GET http://localhost:3000/api/v1/tuote


###get tuote by id
GET http://localhost:3000/api/v1/tuote/17

###get tuote by tyyppi id
GET http://localhost:3000/api/v1/tuote/tyyppi_id/2

###get tuote by user id
GET http://localhost:3000/api/v1/tuote/maara/12

### getviimeinen tuote id
GET http://localhost:3000/api/v1/tuote/lastid/

### get kategoria by name
GET http://localhost:3000/api/v1/tuote/name/jääkahvi


### uusi tuote
POST http://localhost:3000/api/v1/tuote
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tuote_nimi"

Custom Kakku
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tuote_kuvaus"

Tarjoamme uniikkeja kustomoituja kakkuja, jotka luodaan juuri asiakkaan toiveiden mukaan. Kun teet tilauksen, olemme yhteydessä sähköpostitse varmistaaksemme kaikki yksityiskohdat. Teemme kakkuja erilaisiin tilaisuuksiin, kuten syntymäpäiviin, häihin ja yritystapahtumiin, ja varmistamme, että lopputulos halujesi mukainen.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tuote_hinta"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tuote_kustannus"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tyyppi_id"

2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="tuote_kuva"; filename="custom.jpg"
Content-Type: image/jpeg

< kuvat/kakut/custom.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###Delete tuote by id
DELETE http://localhost:3000/api/v1/tuote/2

#

###Update tuote by id, käydä postman to update
PUT http://localhost:3000/api/v1/tuote/2
Content-Type: from-data

{
    "tuote_nimi": "mansikkakakku_pala",
    "tuote_kuva": "",
    "tuote_hinta": "3.25",
    "tuote_kustannus": "2.00",
    "tyyppi_id": ""
}

### get tuote by id lang ja hinta
GET http://localhost:3000/api/v1/tuote/137/EN/51.00


### get tuote by id lang 
GET http://localhost:3000/api/v1/tuote/FI/51.00