POST http://localhost:3000/api/v1/asiakas
Content-Type: application/json

{
    "asiakas_id": "1",
    "asiakas_etunimi": "Anna",
    "asiakas_sukunimi": "Ansku",
    "asiakas_tunnus": "anna",
    "asiakas_salasana": "12345",
    "role": "admin",
    "asiakas_email": "anna@ascafe.fi",
    "asiakas_puh": "1234567",
    "asiakas_registeri_pvm": "2009-04-09"
}
### post new user


POST http://localhost:3000/api/v1/asiakas
Content-Type: application/json

{
    "asiakas_id": "2",
    "asiakas_etunimi": "Matti",
    "asiakas_sukunimi": "Meikäläinen",
    "asiakas_tunnus": "matti",
    "asiakas_salasana": "12345",
    "asiakas_email": "matti@ascafe.fi",
    "asiakas_puh": "1234567",
    "asiakas_registeri_pvm": "2009-04-09"

}
### Get single cat
GET http://127.0.0.1:3000/api/v1/cats/41
