###
GET http://localhost:3000/api/v1/yritystoiminta


###get yritystoiminta by id
GET http://localhost:3000/api/v1/yritystoiminta/1


###get yritystoiminta by tilaus_pvm
GET http://localhost:3000/api/v1/yritystoiminta/pvm/2021-01-29

###get all palaute between dates
GET http://localhost:3000/api/v1/yritystoiminta/2021-01-19/2021-01-29


### uusi yritystoiminta
POST http://localhost:3000/api/v1/yritystoiminta
Content-Type: application/json

{
    "tapahtu_pvm": "2021-01-19",
    "tilaus_id": "1",
    "myynti_hinta": "",
    "myynti_summa": "",
    "kustannus": "",
    "kustannus": "",
    "voitto": ""
}



###Delete yritystoiminta by id
DELETE http://localhost:3000/api/v1/yritystoiminta/1


###Update yritystoiminta by id
PUT http://localhost:3000/api/v1/yritystoiminta/2
Content-Type: application/json

{
    "tapahtu_pvm": "2021-01-19",
    "tilaus_id": "1",
    "myynti_hinta": "",
    "myynti_summa": "",
    "kustannus": "",
    "kustannus": "",
    "voitto": ""
}
